language: haskell
ghc:
    - 7.6
    - 7.8
env:
    - TEST_PKG=users
    - TEST_PKG=users-test
    - TEST_PKG=users-postgresql-simple
script:
    chmod +x ./check-package.sh && ./check-package.sh $TEST_PKG
